# Site settings
title: Squeak/Smalltalk
copyright: Squeak.org
url: https://squeak.org

# SEO
author: Squeak.org
description: >-
  Squeak is a modern, open source, full-featured implementation of the powerful
  Smalltalk programming language and environment.
twitter:
  username: squeaksmalltalk
logo: /static/img/squeak.png
social:
  name: Squeak.org
  links:
    - https://twitter.com/squeaksmalltalk
    - https://github.com/squeak-smalltalk
    - https://www.linkedin.com/groups/98736

collections:
  # Order matters
  features:
    title: Features
    sort_by: order
  downloads:
    title: Downloads
    sort_by: order
  community:
    title: Community
    sort_by: order
  projects:
    title: Projects
    sort_by: title
  documentation:
    title: Documentation
    sort_by: order
    visible-sm: <i class="fa fa-book"></i>
    mobile-title: Docs
  development:
    title: Development
    sort_by: order
    visible-sm: "[ | ]"
  research:
    title: Research
    visible-sm: <i class="fa fa-flask"></i>
    sort_by: order

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      cols: 6
      href-external: true
  -
    scope:
      path: ""
      type: "research"
    values:
      cols: 12

# Enable SASS support
sass:
  sass_dir: _sass
  style: :compressed

# Serving
host: 0.0.0.0

# Caching
build_version: 1.5
staticurl: static/

# Build settings
highlighter: pygments
markdown: kramdown

# Enable plugins
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll/scholar
  - jekyll-sitemap  # Should be at the end of the list

include: [_pages]

# Exclude vendor dir which Travis uses to bundle all gems on its build servers
exclude: [vendor, README.md, _research/references.bib, Gemfile, Rakefile]

# jekyll-scholar
scholar:
  sort_by: none
  order: ascending

  source: _research
  bibliography: references.bib
  bibliography_template: bib
  style: _research/squeak.csl
